### ISSUE TITLE
TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by RPG3D** [ncsoft/Unreal.js-core#34]
hi
  when I run your demo project, meet an error

Javascript: Error: TypeError: Cannot read property 'spawnTab' of undefined
MapCheck: Map check complete: 0 Error(s), 0 Warning(s), took 37.652ms to complete.
Javascript: Error: file:///d:/Program%20Files/Epic%20Games/UE_4.19/Engine/Plugins/Marketplace/UnrealJS/Content/Scripts/devrequire.js:19: TypeError: require(...) is not a function
Javascript: Error: TypeError: require(...) is not a function
Javascript: Error:     at default_exec (file:///d:/Program%20Files/Epic%20Games/UE_4.19/Engine/Plugins/Marketplace/UnrealJS/Content/Scripts/devrequire.js:19:31)
Javascript: Error:     at devrequire (file:///d:/Program%20Files/Epic%20Games/UE_4.19/Engine/Plugins/Marketplace/UnrealJS/Content/Scripts/devrequire.js:26:19)
Javascript: Error:     at module.exports (file:///e:/UEProject/Unreal.js-demo-4.19/Content/Scripts/bootstrap.js:12:30)
Javascript: Error:     at file:///e:/UEProject/Unreal.js-demo-4.19/Content/Scripts/app.js:19:25
Javascript: Error:     at file:///e:/UEProject/Unreal.js-demo-4.19/Content/Scripts/app.js:21:3

**Comment by imre-chroncsik** [comment]
Not sure about the exact reasons, but I noticed that since the 4.19 update, app.js now does `require('bootstrap')(__filename)` while previous versions did `require('bootstrap')('app')`. For me this new code causes 'require(...) is not a function', reverting to 'app' fixes it.
